const requests = [
  {
    id: 1,
    bloodType: "B+",
    name: "Ronald Dixon",
    age: 24,
    gender: "Male",
    location: "Sadar, Pakistan",
    contact: "091-1234567890",
    distance: 28,
    time: 12,
    priority: "urgent",
  },
  {
    id: 2,
    bloodType: "O-",
    name: "Kathy Bates",
    age: 19,
    gender: "Female",
    location: "Gulbahar, Pakistan",
    contact: "091-1234567891",
    distance: 10,
    time: 22,
    priority: "urgent",
  },
  {
    id: 3,
    bloodType: "A+",
    name: "Edward Sanders",
    age: 6,
    gender: "Male",
    location: "Bilal Town, Pakistan",
    contact: "091-1234567892",
    distance: 15.3,
    time: 24,
    priority: "urgent",
  },
];
const allRequests = [
  {
    id: 1,
    bloodType: "B+",
    name: "Ronald Dixon",
    age: 24,
    gender: "Male",
    location: "Gulbahar, Pakistan",
    contact: "091-1234567891",
    distance: 28,
    time: 12,
    priority: "urgent",
  },
  {
    id: 2,
    bloodType: "O-",
    name: "Kathy Bates",
    age: 19,
    gender: "Female",
    location: "Sadar, Pakistan",
    contact: "091-1234567890",
    distance: 10,
    time: 22,
    priority: "urgent",
  },
  {
    id: 3,
    bloodType: "A+",
    name: "Edward Sanders",
    age: 6,
    gender: "Male",
    location: "Bilal Town, Pakistan",
    contact: "091-1234567892",
    distance: 15.3,
    time: 24,
    priority: "urgent",
  },
  {
    id: 4,
    bloodType: "B+",
    name: "Ronald Dixon",
    age: 24,
    gender: "Male",
    location: "Bilal Town, Pakistan",
    contact: "091-1234567892",
    distance: 28,
    time: 12,
    priority: "urgent",
  },
  {
    id: 5,
    bloodType: "O-",
    name: "Kathy Bates",
    age: 19,
    gender: "Female",
    location: "Bilal Town, Pakistan",
    contact: "091-1234567892",
    distance: 10,
    time: 22,
    priority: "urgent",
  },
  {
    id: 6,
    bloodType: "A+",
    name: "Edward Sanders",
    age: 6,
    gender: "Male",
    location: "Bilal Town, Pakistan",
    contact: "091-1234567892",
    distance: 15.3,
    time: 24,
    priority: "urgent",
  },
  {
    id: 7,
    bloodType: "O-",
    name: "Kathy Bates",
    age: 19,
    gender: "Female",
    location: "Bilal Town, Pakistan",
    contact: "091-1234567892",
    distance: 10,
    time: 22,
    priority: "urgent",
  },
  {
    id: 8,
    bloodType: "A+",
    name: "Edward Sanders",
    age: 6,
    gender: "Male",
    location: "Bilal Town, Pakistan",
    contact: "091-1234567892",
    distance: 15.3,
    time: 24,
    priority: "urgent",
  },
];

const allAvailables = [
  {
    id: 1,
    bloodType: "B+",
    name: "Ronald Dixon",
    age: 24,
    gender: "Male",
    location: "Bilal Town, Pakistan",
    contact: "091-1234567892",
    distance: 28,
    time: 12,
    priority: "urgent",
  },
  {
    id: 2,
    bloodType: "O-",
    name: "Kathy Bates",
    age: 19,
    gender: "Female",
    location: "Bilal Town, Pakistan",
    contact: "091-1234567892",
    distance: 10,
    time: 22,
    priority: "urgent",
  },
  {
    id: 3,
    bloodType: "A+",
    name: "Edward Sanders",
    age: 6,
    gender: "Male",
    location: "Bilal Town, Pakistan",
    contact: "091-1234567892",
    distance: 15.3,
    time: 24,
    priority: "urgent",
  },
  {
    id: 4,
    bloodType: "B+",
    name: "Ronald Dixon",
    age: 24,
    gender: "Male",
    location: "Bilal Town, Pakistan",
    contact: "091-1234567892",
    distance: 28,
    time: 12,
    priority: "urgent",
  },
  {
    id: 5,
    bloodType: "O-",
    name: "Kathy Bates",
    age: 19,
    gender: "Female",
    location: "Bilal Town, Pakistan",
    contact: "091-1234567892",
    distance: 10,
    time: 22,
    priority: "urgent",
  },
  {
    id: 6,
    bloodType: "A+",
    name: "Edward Sanders",
    age: 6,
    gender: "Male",
    location: "Bilal Town, Pakistan",
    contact: "091-1234567892",
    distance: 15.3,
    time: 24,
    priority: "urgent",
  },
];

const donations = [
  {
    id: 1,
    bloodType: "B+",
    name: "Ronald Dixon",
    age: 24,
    gender: "Male",
    location: "Bilal Town, Pakistan",
    contact: "091-1234567892",
    distance: 28,
    time: 12,
    priority: "urgent",
  },
  {
    id: 2,
    bloodType: "O-",
    name: "Kathy Bates",
    age: 19,
    gender: "Female",
    location: "Bilal Town, Pakistan",
    contact: "091-1234567892",
    distance: 10,
    time: 22,
    priority: "urgent",
  },
];
const chart = [
  1.1, 3, 1.5, 2.3, 3.2, 7, 8.2, 1.2, 1.5, 1.2, 8, 3.8, 5.8, 3.9, 5.1, 0.1, 1,
];

const user = {
  avatar: require("../assets/avatar.png"),
};

export { requests, chart, user, donations, allRequests, allAvailables };
